= PREFACE

To the Reader -- 

As many false reports have been circulated respecting the following work, and also many unlawful measures taken by evil designing persons to destroy me, and also the work, I would inform you that I translated, by the gift and power of God, and caused to be written, one hundred and sixteen pages, the which I took from the Book of Lehi, which was an account abridged from the plates of Lehi, by the hand of Mormon; which said account, some person or persons have stolen and kept from me, notwithstanding my utmost exertions to recover it again -- and being commanded of the Lord that I should not translate the same over again, for Satan had put it into their hearts to tempt the Lord their God, by altering the words that they did read contrary from that which I translated and caused to be written; and if I should bring forth the same words again, or, in other words, if I should translate the same over again, they would publish that which they had stolen, and Satan would stir up the hearts of this generation, that they might not receive this work: but behold the Lord said unto me, I will not suffer that Satan shall accomplish his evil design in this thing: therefore thou shalt translate from the plates of Nephi, until ye come to that which ye have translated, which ye have retained; and behold ye shall publish it as a record of Nephi; and thus I will confound those who have altered my words. I will not suffer that they shall destroy my work; yea, I will shew unto them that my wisdom is greater then the cunning of the Devil. Wherefore, to be obedient unto the commandments of God, I have, through his grace and mercy, accomplished that which he hath commanded me respecting this thing. I would also inform you that the plates of which hath been spoken, were found in the township of Manchester, Ontario county, New-York.

The Author.    
